name: MacOS

defaults:
  run:
    shell: bash

on: push

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      matrix:
        cxx:
          - g++-10
          - clang++
        configs: [Release, Debug]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure build
        working-directory: ${{runner.workspace}}
        env:
          CXX: ${{matrix.cxx}}
        run: |
          cmake -Bbuild -H$GITHUB_WORKSPACE \
                -DCMAKE_BUILD_TYPE=${{matrix.configs}} \
                -DSTRUCTURA_TESTS=ON

      - name: Build library & tests
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config "${{matrix.configs}}"

      - name: Run tests
        working-directory: ${{runner.workspace}}/build
        run: ./StructuraTests

      - name: Check memory leaks
        working-directory: ${{runner.workspace}}/build
        run: leaks --atExit -- ./StructuraTests
